### ISSUE TITLE
The library is not RFC 5322-compliant

### ISSUE THREAD

**Issue by ptrcnull** [Sayan751/email-address-parser#8]
More specifically, the RFC defines address as:
```
address         =   mailbox / group
mailbox         =   name-addr / addr-spec
name-addr       =   [display-name] angle-addr
angle-addr      =   [CFWS] "<" addr-spec ">" [CFWS] /
                       obs-angle-addr
group           =   display-name ":" [group-list] ";" [CFWS]
```
This library parses only the second case for `mailbox` - `addr-spec`, thus the "An RFC 5322, and RFC 6532 compliant email address parser" tagline is misleading

**Comment by Sayan751** [comment]
@ptrcnull Thank you for submitting the issue. The package is only focused on parsing the email addresses, and what you have pointed out had never been in the scope of this package. 

However, I have updated the readme to reflect this limitation. With that change in place, I would like to close this issue. I would also appreciate a PR with the changes in the parser, in case you are interested.
